#!/usr/bin/env bash
# Displays information about subdomains of a given domain.
# shellcheck disable=SC2086

# Function to display subdomain info
display_subdomain_info() {
    local domain=$1
    local subdomain=$2
    local info
    
    info=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/ {flag=1; next} flag && /^[^;]/ {print $4, $5; exit}')
    
    if [ -n "$info" ]; then
        local record_type
        record_type=$(echo "$info" | awk '{print $1}')
        local destination
        destination=$(echo "$info" | awk '{print $2}')

        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    fi
}
    
DOMAIN=$1
SUBDOMAIN=$2

if [ -z "$SUBDOMAIN" ]; then
    display_subdomain_info "$DOMAIN" "www"
    display_subdomain_info "$DOMAIN" "lb-01"
    display_subdomain_info "$DOMAIN" "web-01"
    display_subdomain_info "$DOMAIN" "web-02"
else
    display_subdomain_info "$DOMAIN" "$SUBDOMAIN"
fi