#!/usr/bin/env bash
# Script that displays information about subdomains
# Usage: ./0-world_wide_web <domain> [subdomain]

# shellcheck disable=SC2086

audit_subdomain () {
    local domain=$1
    local subdomain=$2
    local result
    result=$(dig $subdomain.$domain | grep -A1 'ANSWER SECTION:' | tail -1)
    local record_type
    record_type=$(echo $result | awk '{print $4}')
    local destination
    destination=$(echo $result | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    audit_subdomain $domain www
    audit_subdomain $domain lb-01
    audit_subdomain $domain web-01
    audit_subdomain $domain web-02
else
    audit_subdomain $domain $subdomain
fi